# Generated by Django 5.2.3 on 2025-06-21 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("filename", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("natural_language_query", models.TextField()),
                ("generated_regex", models.TextField(blank=True)),
                ("replacement_value", models.TextField()),
                ("target_column", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.fileupload"
                    ),
                ),
            ],
        ),
    ]
